kind: pipeline
name: default
type: docker

steps:
  - name: build
    image: tystuyfzand/goc:latest
    volumes:
      - name: build
        path: /build
    commands:
      - mkdir -p /build
      - goc -o /build/goc
    environment:
      GOOS: linux,windows,darwin
      GOARCH: 386,amd64,arm,arm64
  - name: docker
    image: plugins/docker
    volumes:
      - name: build
        path: /build
      - name: dockersock
        path: /var/run/docker.sock
    settings:
      username:
        from_secret: docker_username
      password:
        from_secret: docker_password
      repo: tystuyfzand/goc
      tags:
        - latest
volumes:
  - name: build
    temp: {}
  - name: dockersock
    host:
      path: /var/run/docker.sock