kind: pipeline
name: default
type: docker

steps:
  - name: build
    image: tystuyfzand/goc:latest
    volumes:
      - name: build
        path: /build
    commands:
      - mkdir -p /build
      - goc -o /build/goc
    environment:
      GOOS: linux,windows,darwin
      GOARCH: 386,amd64,arm,arm64
  - name: tags
    image: alpine
    volumes:
      - name: build
        path: /build
    commands:
      - echo "go${GO_VERSION:-1.20}" > .tags
    when:
      ref:
        - refs/tags/*
  - name: docker
    image: plugins/docker
    settings:
      username:
        from_secret: docker_username
      password:
        from_secret: docker_password
      repo: tystuyfzand/goc
      build_args:
        - BASE_IMAGE=golang:${GO_VERSION:-1.20}-alpine
    when:
      ref:
        - refs/tags/*
volumes:
  - name: build
    temp: {}