kind: pipeline
name: default
type: docker

steps:
  - name: build
    image: tystuyfzand/goc:latest
    volumes:
      - name: build
        path: /build
    commands:
      - mkdir -p /build
      - goc -o /build/goc
    environment:
      GOOS: linux,windows,darwin
      GOARCH: 386,amd64,arm,arm64
  - name: docker
    image: plugins/docker
    settings:
      username:
        from_secret: docker_username
      password:
        from_secret: docker_password
      repo: tystuyfzand/goc
      tags:
        - '${GO_VERSION}'
        - latest
      build_args_from_env:
        - GO_VERSION
volumes:
  - name: build
    temp: {}